# Generated by Django 4.2.10 on 2024-02-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_account_email_remove_account_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
    ]
