# Generated by Django 4.2.10 on 2024-02-14 12:21

from django.db import migrations


def create_data(apps, schema_editor):

    Account = apps.get_model('account', 'Account')

    user1 = Account.objects.create(username='user1', password='password1', full_name='User One')
    user2 = Account.objects.create(username='user2', password='password2', full_name='User Two')

    Comment = apps.get_model('account', 'Comment')
    comment = Comment.objects.create(from_account=user1, message='Hello User Two!', to_account=user2)


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_picture'),
    ]

    operations = [migrations.RunPython(create_data)]
